[package]
name = "mathlib_rust"
version = "0.1.0"
authors = ["devonwebbR2K <devonwebb559@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.6"
rand = "0.8.5"